name: kios_agro
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  firebase: ^7.2.1
  firebase_auth: ^0.15.5+3
  firebase_database: ^3.1.3
  firebase_core: ^0.4.4+3
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.3.0
  http: ^0.12.0+4
  dio: ^3.0.9
  carousel_slider: ^1.4.1
  splashscreen: ^1.2.0
  url_launcher: ^5.4.2
  image_picker: ^0.6.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - logo2.png
    - google_logo.png
    - bg_login.png
    - jne.jpg
    - jnt.jpg
    - tiki.jpg
    - lion.jpg
    - pos.jpg
    - sicepat.jpg
